// export const companyListFixed = [
//   {
//     name: "stockx",
//     url: "stockx.com",
//     cbSlug: "stockx",
//     displayedName: "StockX",
//     logo: "https://images.crunchbase.com/image/upload/t_cb-default-original/hvhqzscb7we0hifjqr2q",
//     appId: "1000600000607381",
//     linkedInSlug: "stockx",
//   },
//   {
//     name: "goat",
//     url: "goat.com",
//     cbSlug: "goatapp",
//     displayedName: "GOAT",
//     logo: "https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/vtpvp46fr98de2r1txof",
//     appId: "1000600000606873",
//     linkedInSlug: "goatgroup",
//   },
//   {
//     name: "grailed",
//     url: "grailed.com",
//     cbSlug: "grailed",
//     displayedName: "Grailed",
//     logo: "https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/cy5oo3m3njxtojnvz198",
//     appId: "1000600000657044",
//     linkedInSlug: "grailed",
//   },
//   {
//     name: "flight-club",
//     url: "flightclub.com",
//     cbSlug: "flight-club-new-york-ltd",
//     displayedName: "Flight Club",
//     logo: "https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/v1423006341/cmctwzqw4fhxhuhv7zwh.png",
//     appId: null,
//   },
//   {
//     name: "zillow",
//     url: "zillow.com",
//     cbSlug: "zillow",
//     displayedName: "Zillow",
//     logo: "https://images.crunchbase.com/image/upload/t_cb-default-original/v1500275099/j2jcc1e5txlw573hwrd2.png",
//     appId: "1000600000438182",
//   },
//   // {
//   //   name: "hinge",
//   //   url: "hinge.co",
//   //   cbSlug: "hinge",
//   //   displayedName: "Hinge",
//   //   logo: "https://images.crunchbase.com/image/upload/t_cb-default-original/v1476208888/ioqpyzju0fzjm4hinlsk.jpg",
//   // },
//   {
//     name: "tinder",
//     url: "tinder.com",
//     cbSlug: "tinder",
//     displayedName: "Tinder",
//     logo: "https://images.crunchbase.com/image/upload/t_cb-default-original/v1493769757/m6qsmngji1qacb480jeg.png",
//     appId: "1000600000001791",
//   },
//   {
//     name: "bumble",
//     url: "bumble.com",
//     cbSlug: "bumble",
//     displayedName: "Bumble",
//     logo: "https://images.crunchbase.com/image/upload/t_cb-default-original/g9hbkpvy3xxyo3dzryst",
//     appId: "1000600000525199",
//   },
// ];
export const companyListTop50 = [
  {
    name: "Openai",
    url: "openai.com",
    displayedName: "Openai",
    appId: "1000600000851487",
    appName: "ChatGPT",
    linkedInSlug: "openai",
    Description:
      "OpenAI is an AI research and deployment company that conducts research and implements machine learning.",
    headquarter_country: "USA",
    founded_in_year: "2015",
    "Total Funding Amount (Amount)": "11300120000",
    "Funding Stage (Type)": "Seed",
    "Last Funded In (Date)": "Dec 2023",
    "Employee Count (Jan 24)": "1413",
  },
  {
    name: "WeWork",
    url: "wework.com",
    displayedName: "WeWork",
    appId: null,
    appName: null,
    linkedInSlug: "wework",
    Description:
      "WeWork is a platform for creators that transforms buildings into dynamic environments for creativity, focus, and collaboration.",
    headquarter_country: "USA",
    founded_in_year: "2010",
    "Total Funding Amount (Amount)": "21745784331",
    "Funding Stage (Type)": "Public",
    "Last Funded In (Date)": "Jan 2023",
    "Employee Count (Jan 24)": "5868",
  },
  {
    name: "Sword Health",
    url: "swordhealth.com",
    displayedName: "Sword Health",
    appId: "1000600000859991",
    appName: "Sword Health",
    linkedInSlug: "swordhealth",
    Description:
      "Sword Health is a digital musculoskeletal therapy provider that pairs its members with a licensed physical therapist.",
    headquarter_country: "USA",
    founded_in_year: "2015",
    "Total Funding Amount (Amount)": "323466017",
    "Funding Stage (Type)": "Series D",
    "Last Funded In (Date)": "Nov 2021",
    "Employee Count (Jan 24)": "766",
  },
  {
    name: "Hinge Health",
    url: "hingehealth.com",
    displayedName: "Hinge Health",
    appId: "1000600000815130",
    appName: "Hinge Health",
    linkedInSlug: "hinge-health",
    Description:
      "Hinge Health is a digital clinic for joint, and muscle care, pelvic pain, bowel, and bladder control.",
    headquarter_country: "USA",
    founded_in_year: "2015",
    "Total Funding Amount (Amount)": "1026132500",
    "Funding Stage (Type)": "Series E",
    "Last Funded In (Date)": "Oct 2021",
    "Employee Count (Jan 24)": "1579",
  },
  {
    name: "Maven Clinic",
    url: "mavenclinic.com",
    displayedName: "Maven Clinic",
    appId: "1000600000708665",
    appName: "Maven Clinic",
    linkedInSlug: "mavenclinic",
    Description:
      "Maven is a digital health platform that works with health plans and employers to offer virtual services for women\u2019s and family health.",
    headquarter_country: "USA",
    founded_in_year: "2014",
    "Total Funding Amount (Amount)": "292100000",
    "Funding Stage (Type)": "Series E",
    "Last Funded In (Date)": "Nov 2022",
    "Employee Count (Jan 24)": "957",
  },
  {
    name: "Ro Health",
    url: "rohealth.com",
    displayedName: "Ro Health",
    appId: null,
    appName: null,
    linkedInSlug: "ro-health",
    Description:
      "Ro Health provides medical staffing and home health services.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "0",
    "Funding Stage (Type)": "Unfunded",
    "Last Funded In (Date)": null,
    "Employee Count (Jan 24)": "539",
  },
  {
    name: "Hims",
    url: "forhims.com",
    displayedName: "Hims",
    appId: "1000600000833636",
    appName: "Hims: Telehealth for Men",
    linkedInSlug: "hims-%26-hers",
    Description:
      "Hims is a wellness brand that helps men and women get access to products for skin care, hair loss, and sexual health.",
    headquarter_country: "USA",
    founded_in_year: "2017",
    "Total Funding Amount (Amount)": "233200000",
    "Funding Stage (Type)": "Public",
    "Last Funded In (Date)": "Jan 2021",
    "Employee Count (Jan 24)": "987",
  },
  {
    name: "Talkspace",
    url: "talkspace.com",
    displayedName: "Talkspace",
    appId: "1000600000536414",
    appName: "Talkspace",
    linkedInSlug: "talkspace-online-therapy",
    Description:
      "Talkspace is a digital therapy company that offers online therapy, online counseling, psychiatry and medication management, and self-care.",
    headquarter_country: "USA",
    founded_in_year: "2012",
    "Total Funding Amount (Amount)": "413700000",
    "Funding Stage (Type)": "Public",
    "Last Funded In (Date)": "Jun 2021",
    "Employee Count (Jan 24)": "926",
  },
  {
    name: "BetterHelp",
    url: "betterhelp.com",
    displayedName: "BetterHelp",
    appId: "1000600000566396",
    appName: "BetterHelp",
    linkedInSlug: "betterhelp",
    Description:
      "BetterHelp is an online counseling platform that connects its members to licensed therapists.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "0",
    "Funding Stage (Type)": "Merged or Acquired",
    "Last Funded In (Date)": null,
    "Employee Count (Jan 24)": "3312",
  },
  {
    name: "Cerebral",
    url: "cerebral.com",
    displayedName: "Cerebral",
    appId: "1000600000852592",
    appName: "Cerebral - Mental Health",
    linkedInSlug: "getcerebral",
    Description:
      "Cerebral is a mental health telemedicine company that is democratizing access to high quality mental health care for all.",
    headquarter_country: "USA",
    founded_in_year: "2020",
    "Total Funding Amount (Amount)": "462000000",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Dec 2021",
    "Employee Count (Jan 24)": "894",
  },
  {
    name: "Headspace",
    url: "headspace.com",
    displayedName: "Headspace",
    appId: "1000600000457477",
    appName: "Headspace",
    linkedInSlug: "headspace-meditation-limited",
    Description:
      "Headspace specializes in providing mental healthcare, including coaching therapy and psychiatry, as well as meditation mindfulness tools.",
    headquarter_country: "USA",
    founded_in_year: "2010",
    "Total Funding Amount (Amount)": "320853477",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Jul 2023",
    "Employee Count (Jan 24)": "1427",
  },
  {
    name: "TikTok",
    url: "tiktok.com",
    displayedName: "TikTok",
    appId: "1000600000575007",
    appName: "TikTok",
    linkedInSlug: "tiktok",
    Description:
      "TikTok is a short-video sharing app and social network platform that develops a lip-syncing video application to create videos.",
    headquarter_country: "USA",
    founded_in_year: "2003",
    "Total Funding Amount (Amount)": "0",
    "Funding Stage (Type)": "Unfunded",
    "Last Funded In (Date)": null,
    "Employee Count (Jan 24)": "58501",
  },
  {
    name: "ByteDance",
    url: "bytedance.com",
    displayedName: "ByteDance",
    appId: null,
    appName: null,
    linkedInSlug: "bytedance",
    Description:
      "ByteDance is an internet technology company that operates creative content platforms.",
    headquarter_country: "China",
    founded_in_year: "2012",
    "Total Funding Amount (Amount)": "9505000000",
    "Funding Stage (Type)": "Private Equity",
    "Last Funded In (Date)": "Mar 2023",
    "Employee Count (Jan 24)": "39295",
  },
  {
    name: "Reibus",
    url: "reibus.com",
    displayedName: "Reibus",
    appId: null,
    appName: null,
    linkedInSlug:
      "reibus%3Ftrk%3Dpublic_profile_experience-item_profile-section-card_subtitle-click",
    Description:
      "Reibus is a B2B digital marketplace for industrial materials.",
    headquarter_country: "USA",
    founded_in_year: "2018",
    "Total Funding Amount (Amount)": "101650000",
    "Funding Stage (Type)": "Series B",
    "Last Funded In (Date)": "Dec-22",
    "Employee Count (Jan 24)": "166",
  },
  {
    name: "LegalZoom",
    url: "legalzoom.com",
    displayedName: "LegalZoom",
    appId: null,
    appName: null,
    linkedInSlug: "legalzoom",
    Description:
      "LegalZoom is a technology platform giving access to professional legal advice so people can protect what matters most.",
    headquarter_country: "USA",
    founded_in_year: "1999",
    "Total Funding Amount (Amount)": "951000000",
    "Funding Stage (Type)": "Public",
    "Last Funded In (Date)": "Sep 2023",
    "Employee Count (Jan 24)": "1410",
  },
  {
    name: "ZenBusiness",
    url: "zenbusiness.com",
    displayedName: "ZenBusiness",
    appId: null,
    appName: null,
    linkedInSlug: "zenbusiness-pbc",
    Description:
      "Zenbusiness offers business products and services that help business owners in starting, running, and growing a business.",
    headquarter_country: "USA",
    founded_in_year: "2015",
    "Total Funding Amount (Amount)": "276960005",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Sep 2022",
    "Employee Count (Jan 24)": "397",
  },
  {
    name: "Klarna",
    url: "klarna.com",
    displayedName: "Klarna",
    appId: "1000600000594772",
    appName: "Klarna",
    linkedInSlug: "klarna",
    Description:
      "Klarna is an e-commerce payment solutions platform for merchants and shoppers.",
    headquarter_country: "Sweden",
    founded_in_year: "2005",
    "Total Funding Amount (Amount)": "4548376760",
    "Funding Stage (Type)": "Private Equity",
    "Last Funded In (Date)": "Jul 2022",
    "Employee Count (Jan 24)": "5665",
  },
  {
    name: "Flexport",
    url: "flexport.com",
    displayedName: "Flexport",
    appId: null,
    appName: null,
    linkedInSlug: "flexport",
    Description:
      "Flexport is a full-service global freight forwarder and logistics platform using modern software to fix the user experience in global trade.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "2699000000",
    "Funding Stage (Type)": "Series E",
    "Last Funded In (Date)": "Jan 2024",
    "Employee Count (Jan 24)": "3160",
  },
  {
    name: "Gympass",
    url: "gympass.com",
    displayedName: "Gympass",
    appId: "1000600000583352",
    appName: "GymPass",
    linkedInSlug: "gympass",
    Description:
      "Gympass provides employees with flexible access to gyms, studios, classes, training, and wellness apps.",
    headquarter_country: "USA",
    founded_in_year: "2012",
    "Total Funding Amount (Amount)": "605000000",
    "Funding Stage (Type)": "Series F",
    "Last Funded In (Date)": "Aug 2023",
    "Employee Count (Jan 24)": "3026",
  },
  {
    name: "Tinder",
    url: "tinder.com",
    displayedName: "Tinder",
    appId: "1000600000001791",
    appName: "Tinder",
    linkedInSlug: "tinder-incorporated",
    Description:
      "Tinder anonymously finds people nearby that like each other and connects them if they are both interested.",
    headquarter_country: "USA",
    founded_in_year: "2012",
    "Total Funding Amount (Amount)": "50000000",
    "Funding Stage (Type)": "Unknown Funding Round",
    "Last Funded In (Date)": "Oct 2017",
    "Employee Count (Jan 24)": "952",
  },
  {
    name: "Bumble",
    url: "bumble.com",
    displayedName: "Bumble",
    appId: "1000600000525199",
    appName: "Bumble App",
    linkedInSlug: "bumbleinc",
    Description:
      "Bumble is a social networking platform focused on making romance, friendship, and business connections.",
    headquarter_country: "USA",
    founded_in_year: "2014",
    "Total Funding Amount (Amount)": "313500000",
    "Funding Stage (Type)": "Public",
    "Last Funded In (Date)": "Mar 2023",
    "Employee Count (Jan 24)": "1709",
  },
  {
    name: "DoorDash (doordash.com)",
    url: "doordash.com",
    displayedName: "DoorDash",
    appId: "1000600000438925",
    appName: "DoorDash",
    linkedInSlug: "doordash",
    Description:
      "DoorDash is a food delivery platform that connects customers with local and national business.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "2471820000",
    "Funding Stage (Type)": "Public",
    "Last Funded In (Date)": "Jun 2020",
    "Employee Count (Jan 24)": "52460",
  },
  {
    name: "Uber",
    url: "uber.com",
    displayedName: "Uber",
    appId: "1000600000002718",
    appName: "Uber",
    linkedInSlug: "uber-com",
    Description:
      "Uber develops, markets, and operates a ride-sharing mobile application that allows consumers to submit a trip request.",
    headquarter_country: "USA",
    founded_in_year: "2009",
    "Total Funding Amount (Amount)": "25212450000",
    "Funding Stage (Type)": "Public",
    "Last Funded In (Date)": "Sep 2020",
    "Employee Count (Jan 24)": "88843",
  },
  {
    name: "GoPuff",
    url: "gopuff.com",
    displayedName: "GoPuff",
    appId: "1000600000607119",
    appName: "Gopuff",
    linkedInSlug: "gopuff",
    Description:
      "Gopuff is a digital delivery service designed to deliver daily essentials within minutes.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "3449710000",
    "Funding Stage (Type)": "Private Equity",
    "Last Funded In (Date)": "May 2022",
    "Employee Count (Jan 24)": "3612",
  },
  {
    name: "Reddit",
    url: "reddit.com",
    displayedName: "Reddit",
    appId: "1000600000532208",
    appName: "Reddit",
    linkedInSlug: "reddit-com",
    Description:
      "Reddit is an online platform that enables users to submit links, create content, and have discussions about the topics of their interest.",
    headquarter_country: "USA",
    founded_in_year: "2005",
    "Total Funding Amount (Amount)": "1329049748",
    "Funding Stage (Type)": "Merged or Acquired",
    "Last Funded In (Date)": "Aug 2021",
    "Employee Count (Jan 24)": "3115",
  },
  {
    name: "X (twitter.com)",
    url: "twitter.com",
    displayedName: "X",
    appId: "1000600000000356",
    appName: "X",
    linkedInSlug: "twitter",
    Description:
      "X is a social networking platform that allows its users to send and read microblogs.",
    headquarter_country: "USA",
    founded_in_year: "2006",
    "Total Funding Amount (Amount)": "12869191511",
    "Funding Stage (Type)": "Unknown Funding Round",
    "Last Funded In (Date)": "Jun 2022",
    "Employee Count (Jan 24)": "2109",
  },
  {
    name: "Turo",
    url: "turo.com",
    displayedName: "Turo",
    appId: "1000600000442258",
    appName: "Turo",
    linkedInSlug: "turo",
    Description:
      "Turo is a peer-to-peer car-sharing marketplace where customers can book vehicles from a community of local hosts.",
    headquarter_country: "USA",
    founded_in_year: "2009",
    "Total Funding Amount (Amount)": "502567273",
    "Funding Stage (Type)": "Series E",
    "Last Funded In (Date)": "Aug 2023",
    "Employee Count (Jan 24)": "1621",
  },
  {
    name: "StockX",
    url: "stockx.com",
    displayedName: "StockX",
    appId: "1000600000607381",
    appName: "StockX",
    linkedInSlug: "stockx",
    Description:
      "StockX is an online marketplace to buy and sell limited edition and high demand sneakers.",
    headquarter_country: "USA",
    founded_in_year: "2015",
    "Total Funding Amount (Amount)": "690000000",
    "Funding Stage (Type)": "Series E",
    "Last Funded In (Date)": "Apr 2021",
    "Employee Count (Jan 24)": "1434",
  },
  {
    name: "Fetch Rewards",
    url: "fetchrewards.com",
    displayedName: "Fetch Rewards",
    appId: "1000600000767173",
    appName: "Fetch",
    linkedInSlug: "fetch-rewards",
    Description:
      "Fetch is a mobile shopping platform that enables users to earn and redeem rewards.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "581849943",
    "Funding Stage (Type)": "Series E",
    "Last Funded In (Date)": "Apr 2022",
    "Employee Count (Jan 24)": "844",
  },
  {
    name: "Whoop (whoop.com)",
    url: "whoop.com",
    displayedName: "Whoop",
    appId: "1000600000809381",
    appName: "WHOOP",
    linkedInSlug: "whoop",
    Description:
      "WHOOP is a performance optimization system that tracks athlete recovery, training, and sleeping hours to help boost performance.",
    headquarter_country: "USA",
    founded_in_year: "2012",
    "Total Funding Amount (Amount)": "404751000",
    "Funding Stage (Type)": "Series F",
    "Last Funded In (Date)": "Aug 2021",
    "Employee Count (Jan 24)": "755",
  },
  {
    name: "Whatnot",
    url: "whatnot.com",
    displayedName: "Whatnot",
    appId: "1000600000804927",
    appName: "Whatnot: Buy Sell Go Live",
    linkedInSlug: "whatnot-inc",
    Description:
      "Whatnot is a live stream platform and marketplace that enables collectors and enthusiasts to connect, buy, and sell verified products.",
    headquarter_country: "USA",
    founded_in_year: "2019",
    "Total Funding Amount (Amount)": "484700000",
    "Funding Stage (Type)": "Series D",
    "Last Funded In (Date)": "Jul 2022",
    "Employee Count (Jan 24)": "683",
  },
  {
    name: "Misfits Market",
    url: "misfitsmarket.com",
    displayedName: "Misfits Market",
    appId: "1000600000849458",
    appName: "Misfits Market",
    linkedInSlug: "misfitsmarket",
    Description:
      "Misfits Market provides a subscription box service for organically sourced produce.",
    headquarter_country: "USA",
    founded_in_year: "2018",
    "Total Funding Amount (Amount)": "526500000",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Apr 2023",
    "Employee Count (Jan 24)": "423",
  },
  {
    name: "ezCater",
    url: "ezcater.com",
    displayedName: "ezCater",
    appId: null,
    appName: null,
    linkedInSlug: "ezcater",
    Description:
      "EzCater is an online catering marketplace that allows individuals to order food from local caterers.",
    headquarter_country: "USA",
    founded_in_year: "2007",
    "Total Funding Amount (Amount)": "420789999",
    "Funding Stage (Type)": "Series D",
    "Last Funded In (Date)": "Dec 2021",
    "Employee Count (Jan 24)": "880",
  },
  {
    name: "Roofstock",
    url: "roofstock.com",
    displayedName: "Roofstock",
    appId: null,
    appName: null,
    linkedInSlug: "roofstock",
    Description:
      "Roofstock is an online marketplace for investing in leased single-family rental homes.",
    headquarter_country: "USA",
    founded_in_year: "2015",
    "Total Funding Amount (Amount)": "365250000",
    "Funding Stage (Type)": "Series E",
    "Last Funded In (Date)": "Mar 2022",
    "Employee Count (Jan 24)": "386",
  },
  {
    name: "Spotter (spotter.la)",
    url: "spotter.la",
    displayedName: "Spotter",
    appId: null,
    appName: null,
    linkedInSlug: "spotter-inc",
    Description:
      "Spotter provides a financial solution for independent content creators across digital platforms.",
    headquarter_country: "USA",
    founded_in_year: "2019",
    "Total Funding Amount (Amount)": "230649958",
    "Funding Stage (Type)": "Series D",
    "Last Funded In (Date)": "Feb-22",
    "Employee Count (Jan 24)": "218",
  },
  {
    name: "Papa",
    url: "papa.com",
    displayedName: "Papa",
    appId: null,
    appName: null,
    linkedInSlug: "papainc",
    Description:
      "Papa is a company that provides companionship and care to older adults and their families.",
    headquarter_country: "USA",
    founded_in_year: "2017",
    "Total Funding Amount (Amount)": "0",
    "Funding Stage (Type)": "Unknown Funding Round",
    "Last Funded In (Date)": "Jan 2021",
    "Employee Count (Jan 24)": "918",
  },
  {
    name: "Sorare",
    url: "sorare.com",
    displayedName: "Sorare",
    appId: null,
    appName: null,
    linkedInSlug: "sorare",
    Description:
      "Sorare is a global fantasy football game where players can buy, trade, and play with official digital cards.",
    headquarter_country: "France",
    founded_in_year: "2018",
    "Total Funding Amount (Amount)": "739245791",
    "Funding Stage (Type)": "Series B",
    "Last Funded In (Date)": "Sep 2021",
    "Employee Count (Jan 24)": "213",
  },
  {
    name: "Carta (carta.com)",
    url: "carta.com",
    displayedName: "Carta",
    appId: "1000800000175037",
    appName: "Carta - Manage your equity",
    linkedInSlug: "carta--",
    Description:
      "Carta is a global ownership management platform that helps companies, investors, and employees manage equity and ownership.",
    headquarter_country: "USA",
    founded_in_year: "2012",
    "Total Funding Amount (Amount)": "1157600000",
    "Funding Stage (Type)": "Series G",
    "Last Funded In (Date)": "Aug 2021",
    "Employee Count (Jan 24)": "1934",
  },
  {
    name: "Zazzle",
    url: "zazzle.com",
    displayedName: "Zazzle",
    appId: "1000600000528755",
    appName: "Zazzle",
    linkedInSlug: "zazzle",
    Description:
      "Zazzle.com enables users to receive a commission on products that they design, create and sell.",
    headquarter_country: "USA",
    founded_in_year: "1999",
    "Total Funding Amount (Amount)": "46000000",
    "Funding Stage (Type)": "Series B",
    "Last Funded In (Date)": "May 2012",
    "Employee Count (Jan 24)": "1089",
  },
  {
    name: "Strava",
    url: "strava.com",
    displayedName: "Strava",
    appId: "1000600000448216",
    appName: "Strava Run",
    linkedInSlug: "strava-inc.",
    Description:
      "Strava is an online network where runners and cyclists can record their activities, compare performance, and compete with their community.",
    headquarter_country: "USA",
    founded_in_year: "2009",
    "Total Funding Amount (Amount)": "151850000",
    "Funding Stage (Type)": "Series F",
    "Last Funded In (Date)": "Nov-20",
    "Employee Count (Jan 24)": "481",
  },
  {
    name: "Fooda",
    url: "fooda.com",
    displayedName: "Fooda",
    appId: "1000600000644981",
    appName: "Fooda",
    linkedInSlug: "fooda",
    Description:
      "Fooda is a food technology platform that connects restaurants to people while at work.",
    headquarter_country: "USA",
    founded_in_year: "2011",
    "Total Funding Amount (Amount)": "52000000",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Nov 2023",
    "Employee Count (Jan 24)": "442",
  },
  {
    name: "OnXmaps",
    url: "onxmaps.com",
    displayedName: "OnXmaps",
    appId: "1000600000441628",
    appName: "HUNT App",
    linkedInSlug: "onxmaps",
    Description:
      "onxMaps is a Montana-based mobile apps company which provide maps for hunters and other outdoor recreation.",
    headquarter_country: "USA",
    founded_in_year: "2009",
    "Total Funding Amount (Amount)": "195076346",
    "Funding Stage (Type)": "Series B",
    "Last Funded In (Date)": "Oct 2022",
    "Employee Count (Jan 24)": "399",
  },
  {
    name: "Cameo",
    url: "cameo.com",
    displayedName: "Cameo",
    appId: "1000600000674900",
    appName: "Cameo - Personalized Shoutouts",
    linkedInSlug: "bookcameo",
    Description:
      "Cameo is a marketplace where fans can book personalized video shoutout from their favorite people.",
    headquarter_country: "USA",
    founded_in_year: "2017",
    "Total Funding Amount (Amount)": "165710000",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Mar 2021",
    "Employee Count (Jan 24)": "319",
  },
  {
    name: "Hinge",
    url: "hinge.co",
    displayedName: "Hinge",
    appId: "1000600000450503",
    appName: "Hinge",
    linkedInSlug: "hinge-app",
    Description:
      "Hinge is a social discovery network helping users meet new people through an application.",
    headquarter_country: "USA",
    founded_in_year: "2011",
    "Total Funding Amount (Amount)": "20600000",
    "Funding Stage (Type)": "Merged or Acquired",
    "Last Funded In (Date)": "Dec 2014",
    "Employee Count (Jan 24)": "318",
  },
  {
    name: "TodayTix",
    url: "todaytix.com",
    displayedName: "TodayTix",
    appId: "1000600000597845",
    appName: "TodayTix",
    linkedInSlug: "todaytixgroup",
    Description:
      "TodayTix is the premier digital gateway to shows, arts, and cultural experiences.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "88682500",
    "Funding Stage (Type)": "Private Equity",
    "Last Funded In (Date)": "May 2019",
    "Employee Count (Jan 24)": "266",
  },
  {
    name: "Masterworks",
    url: "masterworks.com",
    displayedName: "Masterworks",
    appId: "1000800000179126",
    appName: "Masterworks: Invest in Art",
    linkedInSlug: "masterworks",
    Description:
      "Masterworks is a platform that offers art investment products to the retail investing public.",
    headquarter_country: "USA",
    founded_in_year: "2017",
    "Total Funding Amount (Amount)": "110000000",
    "Funding Stage (Type)": "Series A",
    "Last Funded In (Date)": "Oct 2021",
    "Employee Count (Jan 24)": "250",
  },
  {
    name: "Gametime",
    url: "gametime.co",
    displayedName: "Gametime",
    appId: "1000600000513636",
    appName: "Gametime",
    linkedInSlug: "gametime-united",
    Description:
      "Gametime sells last-minute tickets to the most popular events in sports, music, and theater.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "71599983",
    "Funding Stage (Type)": "Series B",
    "Last Funded In (Date)": "May 2022",
    "Employee Count (Jan 24)": "228",
  },
  {
    name: "Chowbus",
    url: "chowbus.com",
    displayedName: "Chowbus",
    appId: "1000600000608494",
    appName: "Chowbus",
    linkedInSlug: "chowbus",
    Description:
      "Chowbus is a delivery platform that provides authentic Asian food sourced from local independent restaurants and stores.",
    headquarter_country: "USA",
    founded_in_year: "2015",
    "Total Funding Amount (Amount)": "108270000",
    "Funding Stage (Type)": "Series A",
    "Last Funded In (Date)": "Aug 2023",
    "Employee Count (Jan 24)": "164",
  },
  {
    name: "Nanit",
    url: "nanit.com",
    displayedName: "Nanit",
    appId: "1000600000770194",
    appName: "Nanit",
    linkedInSlug: "nanit",
    Description:
      "Nanit is a startup developing smart baby monitors and sleep tracker devices.",
    headquarter_country: "USA",
    founded_in_year: "2016",
    "Total Funding Amount (Amount)": "74600000",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Feb 2021",
    "Employee Count (Jan 24)": "118",
  },
  {
    name: "Raise.com",
    url: "raise.com",
    displayedName: "Raise.com",
    appId: "1000600000523878",
    appName: "Raise",
    linkedInSlug: "raise-com",
    Description:
      "Raise is a marketplace (exchange) for gift cards that is the largest direct-to-consumer seller of digital gift cards in the world.",
    headquarter_country: "USA",
    founded_in_year: "2013",
    "Total Funding Amount (Amount)": "147200000",
    "Funding Stage (Type)": "Series C",
    "Last Funded In (Date)": "Jan 2020",
    "Employee Count (Jan 24)": "95",
  },
];
